function k(b,a,c,d){b.v.Bb(b.fb,a,c,d,void 0)}function l(b,a,c,d){b.v.ia?k(b,a,c,d):b.v.te()._OnMessageFromDOM({type:"event",component:b.fb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.v.D(b.fb,a,c)}function r(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Mb||(b.v.me(b.Ld),b.Mb=!0)}window.Fa=class{constructor(b,a){this.v=b;this.fb=a;this.Mb=!1;this.Ld=()=>this.Ia()}Xc(){}Ia(){}};function aa(b){-1!==b.Va&&(self.clearTimeout(b.Va),b.Va=-1)}
window.je=class{constructor(b){this.Ec=b;this.He=5;this.Va=-1;this.Ob=-Infinity;this.Md=()=>{this.Va=-1;this.Ob=Date.now();this.kb=!0;this.Ec();this.kb=!1};this.od=this.kb=!1}j(){aa(this);this.Md=this.Ec=null}};"use strict";function ba(b,a){n(b,"get-element",c=>{const d=b.ga.get(c.elementId);return a(d,c)})}
window.af=class extends self.Fa{constructor(b,a){super(b,a);this.ga=new Map;this.Dc=!0;r(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=this.ga.get(c);this.Dc&&d.parentElement.removeChild(d);this.ga.delete(c)}],["set-visible",c=>{this.Dc&&(this.ga.get(c.elementId).style.display=c.isVisible?"":"none")}],["update-position",c=>{if(this.Dc){var d=this.ga.get(c.elementId);d.style.left=c.left+"px";d.style.top=c.top+"px";d.style.width=c.width+"px";d.style.height=
c.height+"px";c=c.fontSize;null!==c&&(d.style.fontSize=c+"em")}}],["update-state",c=>{this.ga.get(c.elementId);throw Error("required override");}],["focus",c=>this.yc(c)],["set-css-style",c=>{this.ga.get(c.elementId).style[c.prop]=c.val}],["set-attribute",c=>{this.ga.get(c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{this.ga.get(c.elementId).removeAttribute(c.name)}]]);ba(this,c=>c)}yc(b){var a=this.ga.get(b.elementId);b.focus?a.focus():a.blur()}};"use strict";
const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),v=/android/i.test(navigator.userAgent);let da=0;function w(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Re?new Promise(c=>{const d="c3_resolve_"+da;++da;self[d]=c;a.textContent=b.Ve+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ea=!1,fa=!1;
function ha(){if(!ea){try{new Worker("blob://",{get type(){fa=!0}})}catch(b){}ea=!0}return fa}let x=new Audio;const ia={"audio/webm; codecs=opus":!!x.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!x.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!x.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!x.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!x.canPlayType("audio/mp4"),"audio/mpeg":!!x.canPlayType("audio/mpeg")};x=null;
async function ja(b){b=await ka(b);return(new TextDecoder("utf-8")).decode(b)}function ka(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const z=[];let A=0;window.RealFile=window.File;const B=[],D=new Map,E=new Map;let la=0;const ma=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ma.push(b)};const na=new Set(["cordova","playable-ad","instant-games"]);
let oa=!1;
window.qa=class b{constructor(a){this.ia=a.Xe;this.ua=null;this.aa="";this.cc=a.Ue;this.yb={};this.Oa=this.xb=null;this.Kb=[];this.G=this.Ta=null;this.Mc=!1;this.rd=0;this.mb=null;this.Sa=-1;this.Me=()=>this.Ae();this.Ra=[];this.A=a.Nd;this.Nb="file"===location.protocol.substr(0,4);!this.ia||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ha()||(this.ia=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.ia=!1;if("cordova"===this.A&&this.ia)if(v){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&
90<=parseInt(c[1],10)||(this.ia=!1)}else this.ia=!1;this.Rb=this.ma=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.D("runtime","cordova-fetch-local-file",c=>this.we(c));this.D("runtime","create-job-worker",()=>this.xe());"cordova"===this.A?document.addEventListener("deviceready",()=>this.gd(a)):this.gd(a)}j(){this.rc();
this.ua&&(this.ua=this.ua.onmessage=null);this.xb&&(this.xb.terminate(),this.xb=null);this.Oa&&(this.Oa.j(),this.Oa=null);this.G&&(this.G.parentElement.removeChild(this.G),this.G=null)}ge(){return ca&&"cordova"===this.A}nc(){const a=navigator.userAgent;return ca&&na.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ee(){return v}bd(){return v&&na.has(this.A)}async gd(a){"macos-wkwebview"===this.A&&this.Bc({type:"ready"});if("playable-ad"===this.A){this.ma=self.c3_base64files;
this.Rb={};await this.pe();for(let d=0,e=a.Wa.length;d<e;++d){var c=a.Wa[d].toLowerCase();this.Rb.hasOwnProperty(c)?a.Wa[d]={Re:!0,Ve:this.Rb[c]}:this.ma.hasOwnProperty(c)&&(a.Wa[d]=URL.createObjectURL(this.ma[c]))}}a.Te?this.aa=a.Te:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Ze&&(this.yb=a.Ze);c=new MessageChannel;this.ua=c.port1;this.ua.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(d=>this.ze(d));this.mb=new self.he(this);await pa(this.mb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ia?await this.ve(a,c.port2):await this.ue(a,c.port2)}tc(a){a=this.yb.hasOwnProperty(a)?this.yb[a]:a.endsWith("/workermain.js")&&this.yb.hasOwnProperty("workermain.js")?
this.yb["workermain.js"]:"playable-ad"===this.A&&this.ma.hasOwnProperty(a.toLowerCase())?this.ma[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ic(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Nb)return a=await this.zb(d.Qe?a:this.cc+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");
a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}sa(){return Math.max(window.innerWidth,1)}ja(){return Math.max(window.innerHeight,1)}fd(a){var c=this.aa,d=location.href,e=this.sa(),f=this.ja(),g=window.devicePixelRatio,h=b.ab(),m=a.ff,p=window.cr_previewImageBlobs||this.ma,q=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,y=window.df||"";a=a.Nd;var W=(new URLSearchParams(self.location.search)).has("debug"),C=this.mb;return{runtimeBaseUrl:c,previewUrl:d,
windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:t,swClientId:y,exportType:a,isDebug:W,ife:!!self.ef,jobScheduler:{inputPort:C.Lc,outputPort:C.Rc,maxNumWorkers:C.Je},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.cc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.cc+"opus.wasm.wasm",isFileProtocol:this.Nb,isiOSCordova:this.ge(),isiOSWebView:this.nc(),
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async ve(a,c){var d=this.tc(a.Ye);this.xb=await this.ic(d,this.aa,{type:"module",name:"Runtime",Qe:!0});this.G=document.createElement("canvas");this.G.style.display="none";d=this.G.transferControlToOffscreen();document.body.appendChild(this.G);window.c3canvas=this.G;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let e=a.Wc||[],f=a.Wa;e=await Promise.all(e.map(g=>this.Ja(g)));f=await Promise.all(f.map(g=>this.Ja(g)));if("cordova"===
this.A)for(let g=0,h=a.fc.length;g<h;++g){const m=a.fc[g],p=m[0];if(p===a.Uc||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))m[1]=await this.Ja(p)}this.xb.postMessage(Object.assign(this.fd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:d,workerDependencyScripts:e,engineScripts:f,projectScripts:a.fc,mainProjectScript:a.Uc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,d,...ra(this.mb)]);this.Kb=B.map(g=>new g(this));this.ed();self.c3_callFunction=(g,h)=>{var m=this.Ta;
return m.v.dd(m.fb,"js-invoke-function",{name:g,params:h},void 0,void 0)};"preview"===this.A&&(self.goToLastErrorScript=()=>this.Bb("runtime","go-to-last-error-script"))}async ue(a,c){this.G=document.createElement("canvas");this.G.style.display="none";document.body.appendChild(this.G);window.c3canvas=this.G;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Kb=B.map(g=>new g(this));this.ed();var d=a.Wa.map(g=>"string"===typeof g?(new URL(g,this.aa)).toString():g);Array.isArray(a.Wc)&&
d.unshift(...a.Wc);d=await Promise.all(d.map(g=>this.Ja(g)));await Promise.all(d.map(g=>w(g)));d=self.C3_ProjectScriptsStatus;const e=a.Uc,f=a.fc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Ja(h),await w(h),"preview"!==this.A||d[g]||this.jd(g,"main script did not run to completion")}catch(m){this.jd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ja(h),await w(h);"preview"===this.A&&"object"!==typeof self.$e.bf?(this.Fb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.fd(a),{isInWorker:!1,messagePort:c,canvas:this.G,runOnStartupFunctions:ma}),this.hd(),this.Oa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Oa,a))}jd(a,c){this.Fb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}hd(){this.Fb()}Fb(){const a=
window.Oe;a&&(a.parentElement.removeChild(a),window.Oe=null)}async xe(){const a=await sa(this.mb);return{outputPort:a,transferables:[a]}}te(){if(this.ia)throw Error("not available in worker mode");return this.Oa}Bb(a,c,d,e,f){this.ua.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}dd(a,c,d,e,f){const g=la++,h=new Promise((m,p)=>{E.set(g,{resolve:m,reject:p})});this.ua.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.ye(a);if("result"===c)this.Be(a);else if("runtime-ready"===c)this.Ce();else if("alert-error"===c)this.Fb(),alert(a.message);else if("creating-runtime"===c)this.hd();else throw Error(`unknown message '${c}'`);}ye(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=D.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Eb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Eb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Eb(f,!1,""+h)}):this.Eb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Eb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.ua.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Be(a){const c=a.responseId,d=a.isOk;a=a.result;const e=E.get(c);d?e.resolve(a):e.reject(a);E.delete(c)}D(a,
c,d){let e=D.get(a);e||(e=new Map,D.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Xa(a){if(B.includes(a))throw Error("DOM handler already added");B.push(a)}ed(){for(const a of this.Kb)if("runtime"===a.fb){this.Ta=a;return}throw Error("cannot find runtime DOM handler");}ze(a){this.Bb("debugger","message",a)}Ce(){for(const a of this.Kb)a.Xc()}static ab(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
oa)}static Gb(a){oa=!!a}me(a){this.Ra.push(a);this.Ac()}Ee(a){a=this.Ra.indexOf(a);if(-1===a)throw Error("invalid callback");this.Ra.splice(a,1);this.Ra.length||this.rc()}Ac(){-1===this.Sa&&this.Ra.length&&(this.Sa=requestAnimationFrame(this.Me))}rc(){-1!==this.Sa&&(cancelAnimationFrame(this.Sa),this.Sa=-1)}Ae(){this.Sa=-1;for(const a of this.Ra)a();this.Ac()}ya(a){this.Ta.ya(a)}Ha(a){this.Ta.Ha(a)}zc(){this.Ta.zc()}Db(a){this.Ta.Db(a)}fe(){return!!ia["audio/webm; codecs=opus"]}async Fe(a){a=await this.dd("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}ke(a){this.Mc=!0;this.rd=a}de(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}cd(a){return!this.de(a)}async Ja(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Nb&&this.cd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.zb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async we(a){const c=a.filename;switch(a.as){case "text":return await this.ce(c);
case "buffer":return await this.zb(c);default:throw Error("unsupported type");}}$c(a){const c=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ce(a){a=await this.$c(a);return await ja(a)}sc(){if(z.length&&!(8<=A)){A++;var a=z.shift();this.qe(a.filename,a.We,a.Pe)}}zb(a){return new Promise((c,d)=>{z.push({filename:a,We:e=>{A--;this.sc();c(e)},Pe:e=>{A--;this.sc();d(e)}});this.sc()})}async qe(a,
c,d){try{const e=await this.$c(a),f=await ka(e);c(f)}catch(e){d(e)}}Bc(a){if("windows-webview2"===this.A)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.A)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async pe(){const a=[];for(const [c,d]of Object.entries(this.ma))a.push(this.oe(c,d));await Promise.all(a)}async oe(a,c){if("object"===typeof c)this.ma[a]=new Blob([c.str],{type:c.type}),this.Rb[a]=
c.str;else{let d=await this.se(c);d||(d=this.re(c));this.ma[a]=d}}async se(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}re(a){a=this.De(a);return this.ne(a.data,a.Se)}De(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);
c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Se:a,data:d}}ne(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const F=self.qa;
function ta(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const ua=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),G={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},va={dispatchUserScriptEvent:!0},H={dispatchRuntimeEvent:!0};
function wa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function xa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function I(b){b=URL.createObjectURL(b);try{return await xa(b)}finally{URL.revokeObjectURL(b)}}
function ya(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function za(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await I(b);var d=await ya(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await I(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await I(b)}
function J(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Aa=new Set(["input","textarea","datalist","select"]),Ba=new Set(["canvas","body","html"]);function K(b){Ba.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ca(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await I(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await za(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let L=!1;document.addEventListener("pause",()=>L=!0);document.addEventListener("resume",()=>L=!1);async function Da(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ea(b){return await self.C3_GetSvgImageSize(b.blob)}
function Ha(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ia(b){self.setTimeout(()=>{b.qd=!0},1E3);"cordova"===b.v.A?(document.addEventListener("pause",()=>Ja(b,!0)),document.addEventListener("resume",()=>Ja(b,!1))):document.addEventListener("visibilitychange",()=>Ja(b,document.hidden));return{isSuspended:!(!document.hidden&&!L)}}
function Ka(b){b.ld||(b.ld=!0,window.addEventListener("deviceorientation",a=>{b.Y||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},G)}),window.addEventListener("deviceorientationabsolute",a=>{b.Y||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},G)}))}
function La(b){b.kd||(b.kd=!0,window.addEventListener("devicemotion",a=>{if(!b.Y){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},G)}}))}async function Ma(b){await wa(b.url)}
function Na(b,a){b.sd=a.message;-1===b.Hc&&(b.Hc=setTimeout(()=>{b.Hc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.sd)},250))}function M(b){if(!b.Y){var a=F.ab();a&&"any"!==b.Sc&&Oa(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.sa(),innerHeight:b.ja()})}}function Pa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:F.ab(),innerWidth:b.sa(),innerHeight:b.ja()})}
function Ja(b,a){a?b.v.rc():b.v.Ac();k(b,"visibilitychange",{hidden:a})}function Qa(b,a,c){"Backspace"===c.key&&K(c);if(!b.Y){var d=ua.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},G)}}
function Ra(b,a,c,d){b.Y||ta(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Z,pageX:c.pageX,pageY:c.pageY+b.Z,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Sa(b){window!==window.top&&window.focus();Ta(b.target)&&document.activeElement&&!Ta(document.activeElement)&&document.activeElement.blur()}
function N(b,a,c){if(!b.Y){if(b.ub&&"pointermove"!==a){var d=b.ub;d.kb||(aa(d),d.Ob=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.rb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Z,pageX:c.pageX,pageY:c.pageY+b.Z,movementX:(c.movementX||0)+b.Yb,movementY:(c.movementY||0)+b.Zb,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||
0,twist:c.twist||0,timeStamp:c.timeStamp},G);b.Yb=0;b.Zb=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Ra(b,d,c,va),b.rb=c.buttons)}}
function Ua(b,a,c){if(!b.Y&&!ta(c)){var d=b.rb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Z,pageX:c.pageX,pageY:c.pageY+b.Z,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},G);b.rb=c.buttons;Ra(b,c.type,c,va)}}
function O(b,a,c){if(!b.Y)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.Z,pageX:f.pageX,pageY:f.pageY+b.Z,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
G)}}function Va(b,a,c){document.body.style.transform="";b.Z=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.Z=a))}}function Wa(b,a,c,d){const e=b.sa(),f=b.ja();b.Ua=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:F.ab()}):10>d&&Xa(b,e,f,d+1)}
function Xa(b,a,c,d){-1!==b.Ua&&clearTimeout(b.Ua);b.Ua=setTimeout(()=>Wa(b,a,c,d),48)}
function Oa(b){b=b.Sc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ta(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
F.Xa(class extends self.Fa{constructor(b){super(b,"runtime");this.xd=!0;this.Ua=-1;this.Sc="any";this.kd=this.ld=!1;this.Ba=null;this.Y=!1;this.sd="";this.Hc=-1;this.Na=this.ub=null;this.Zb=this.Yb=0;this.qd=!1;this.Bd=b.sa();this.Pb=b.ja();this.Z=this.wb=0;b.D("canvas","update-size",d=>{var e=this.v;e.Mc||(e=e.G,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",this.xd&&(e.style.display="",this.xd=!1))});b.D("runtime",
"invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.D("runtime","raster-svg-image",d=>Da(d));b.D("runtime","get-svg-image-size",d=>Ea(d));b.D("runtime","set-target-orientation",d=>{this.Sc=d.targetOrientation});b.D("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.D("runtime","post-to-debugger",d=>Ha(d));b.D("runtime","go-to-script",d=>
Ha(d));b.D("runtime","before-start-ticking",()=>Ia(this));b.D("runtime","debug-highlight",d=>{if(d.show){this.Ba||(this.Ba=document.createElement("div"),this.Ba.id="inspectOutline",document.body.appendChild(this.Ba));var e=this.Ba;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ba&&(this.Ba.style.display="none")});b.D("runtime","enable-device-orientation",()=>Ka(this));b.D("runtime","enable-device-motion",
()=>La(this));b.D("runtime","add-stylesheet",d=>Ma(d));b.D("runtime","alert",d=>this.wc(d));b.D("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.D("runtime","set-exporting-to-video",d=>{this.Y=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.G.style.display="";this.v.ke(d.duration)});b.D("runtime","export-to-video-progress",
d=>Na(this,d));b.D("runtime","exported-to-video",d=>{window.Ne({type:"exported-video",blob:d.blob,time:d.time})});b.D("runtime","exported-to-image-sequence",d=>{window.Ne({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||J(e)||d.preventDefault()});const c=b.G;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",
K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",K);window.addEventListener("touchstart",K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",K);this.rb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ca,{passive:!1});window.addEventListener("wheel",Ca,{passive:!1});window.addEventListener("resize",
()=>{a:{if(!this.Y){var d=this.sa();var e=this.ja();if(this.v.bd()){if(this.qd){if(this.Bd===d&&e<this.Pb){this.wb=this.Pb-e;Va(this,this.Pb,this.wb);d=void 0;break a}0<this.wb&&(this.wb=0,Va(this,e,this.wb))}this.Bd=d;this.Pb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:F.ab()});this.v.nc()&&(-1!==this.Ua&&clearTimeout(this.Ua),Wa(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>M(this));window.addEventListener("webkitfullscreenchange",
()=>M(this));window.addEventListener("mozfullscreenchange",()=>M(this));window.addEventListener("fullscreenerror",d=>Pa(this,d));window.addEventListener("webkitfullscreenerror",d=>Pa(this,d));window.addEventListener("mozfullscreenerror",d=>Pa(this,d));if(b.nc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;
if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):J(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(F.Gb(!0),M(this)):"exited-fullscreen"===d?(F.Gb(!1),M(this)):console.warn("Unknown wrapper message: ",d)};this.Pa=new Set;this.Tb=new WeakSet;this.ta=!1}Xc(){window.addEventListener("focus",()=>{k(this,"window-focus",
null,H)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},H);this.rb=0});window.addEventListener("focusin",a=>{a=a.target;(Aa.has(a.tagName.toLowerCase())||J(a))&&k(this,"keyboard-blur",null,H)});window.addEventListener("keydown",a=>Qa(this,"keydown",a));window.addEventListener("keyup",a=>Qa(this,"keyup",a));window.addEventListener("dblclick",a=>Ra(this,"dblclick",a,G));window.addEventListener("wheel",
a=>{this.Y||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Z,pageX:a.pageX,pageY:a.pageY+this.Z,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},G)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{Sa(a);N(this,"pointerdown",a)}),this.v.ia&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.ub=new self.je(()=>{N(this,"pointermove",this.Na);this.Na=null}),this.ub.od=!0,window.addEventListener("pointerrawupdate",
a=>{this.Na&&(this.Yb+=this.Na.movementX||0,this.Zb+=this.Na.movementY||0);this.Na=a;a=this.ub;if(-1===a.Va){var c=Date.now(),d=c-a.Ob,e=a.He;d>=e&&a.od?(a.Ob=c,a.kb=!0,a.Ec(),a.kb=!1):a.Va=self.setTimeout(a.Md,Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>N(this,"pointermove",a)),window.addEventListener("pointerup",a=>N(this,"pointerup",a)),window.addEventListener("pointercancel",a=>N(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Sa(a);Ua(this,"pointerdown",a)}),
window.addEventListener("mousemove",a=>Ua(this,"pointermove",a)),window.addEventListener("mouseup",a=>Ua(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Sa(a);O(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>O(this,"pointermove",a)),window.addEventListener("touchend",a=>O(this,"pointerup",a)),window.addEventListener("touchcancel",a=>O(this,"pointercancel",a)));const b=()=>this.zc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",
b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.ee()&&!this.v.bd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Va(this,this.ja(),navigator.virtualKeyboard.boundingRect.height)}))}sa(){return this.v.sa()}ja(){return this.v.ja()}zc(){var b=[...this.Pa];this.Pa.clear();if(!this.ta)for(const a of b)(b=a.play())&&b.catch(()=>{this.Tb.has(a)||this.Pa.add(a)})}ya(b){if("function"!==
typeof b.play)throw Error("missing play function");this.Tb.delete(b);let a;try{a=b.play()}catch(c){this.Pa.add(b);return}a&&a.catch(()=>{this.Tb.has(b)||this.Pa.add(b)})}Ha(b){this.Pa.delete(b);this.Tb.add(b)}Db(b){this.ta=!!b}wc(b){alert(b.message)}});"use strict";
async function pa(b){if(b.Ge)throw Error("already initialised");b.Ge=!0;var a=b.bc.tc("dispatchworker.js");b.Gc=await b.bc.ic(a,b.eb,{name:"DispatchWorker"});a=new MessageChannel;b.Lc=a.port1;b.Gc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Rc=await sa(b)}function ra(b){return[b.Lc,b.Rc]}
async function sa(b){const a=b.yd.length;var c=b.bc.tc("jobworker.js");c=await b.bc.ic(c,b.eb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Gc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.yd.push(c);return e.port1}
self.he=class{constructor(b){this.bc=b;this.eb=b.aa;this.eb="preview"===b.A?this.eb+"workers/":this.eb+b.cc;this.Je=Math.min(navigator.hardwareConcurrency||2,16);this.Gc=null;this.yd=[];this.Rc=this.Lc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.qa({Xe:!1,Ye:"workermain.js",Wa:["scripts/c3runtime.js"],fc:[],Uc:"",Ue:"scripts/",Wc:[],Nd:"html5"}));"use strict";const Za=180/Math.PI;
async function $a(b,a){a.isiOSCordova&&(b.Wb=!0);b.Tc=a.timeScaleMode;b.Ed=["equalpower","HRTF","soundfield"][a.panningModel];b.pd=["linear","inverse","exponential"][a.distanceModel];b.Fd=a.refDistance;b.Dd=a.maxDistance;b.Hd=a.rolloffFactor;if(b.v.Mc)b.Wb=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.rd)});else{var c={latencyHint:a.latencyHint};b.Kd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");ab(b);b.g.onstatechange=()=>{"running"!==b.g.state&&ab(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.La=b.g.createGain();b.La.connect(b.g.destination);c=a.listenerPos;b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",
d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function bb(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,p=a.pos,q=a.panning;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.zd=g;cb(b,g);try{b.la=await db(b,c,d,e,g,f);if(q){Q(b.la,!0);var y=b.la,W=q.innerAngle,C=q.outerAngle,pb=q.outerGain;if(y.lb){eb(y,q.x,q.y,q.angle);var Ga=self.Ya.le;y.F.coneInnerAngle=Ga(W);y.F.coneOuterAngle=
Ga(C);y.F.coneOuterGain=pb}q.hasOwnProperty("uid")&&(b.la.ka=q.uid)}else Q(b.la,!1);b.la.Play(h,m,p,t)}catch(qb){console.error("[Construct] Audio: error starting playback: ",qb);return}finally{c=b.tb.get(g);if(!c)throw Error("expected pending tag");c.Vc--;0===c.Vc&&(c.resolve(),b.tb.delete(g))}u(b)}
async function fb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await gb(b,c);for(const q of R(b,c)){c=q;var f=d,g=e,h=a;if(!c.Ma){var m=c.N.gain;m.cancelScheduledValues(0);var p=c.s.g.currentTime;g=p+g;m.setValueAtTime(m.value,p);m.linearRampToValueAtTime(f,g);c.Ea=f;c.ib=g;c.Jd=h}}S(b)}async function hb(b,a){const c=a.tag;a=a.rate;await gb(b,c);for(const d of R(b,c))b=d,b.ha!==a&&(b.ha=a,b.za())}
async function ib(b,a){const c=a.tag;a=a.pos;await gb(b,c);for(const d of R(b,c))d.oc(a)}async function jb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await db(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function kb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ea.indexOf(a),-1!==a&&b.ea.splice(a,1)}
async function lb(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.Td(b,...e);else if("delay"===c)e=new self.Rd(b,...e);else if("convolution"===c){c=null;try{c=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Qd(b,c.da,...e);var f=a.bufferType;c.md=a.bufferOriginalUrl;c.nd=f}else if("flanger"===c)e=new self.Ud(b,...e);else if("phaser"===c)e=new self.Wd(b,...e);else if("gain"===c)e=
new self.Vd(b,...e);else if("tremolo"===c)e=new self.Yd(b,...e);else if("ringmod"===c)e=new self.Xd(b,...e);else if("distortion"===c)e=new self.Sd(b,...e);else if("compressor"===c)e=new self.Pd(b,...e);else if("analyser"===c)e=new self.Od(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.fa.get(d);e||(e=[],b.fa.set(d,e));a.wd=e.length;a.ba=d;e.push(a);mb(b,d);nb(b)}
async function ob(b,a){const c=a.saveLoadMode;if(3!==c)for(var d of b.L)d.xa()&&1===c||(d.xa()||2!==c)&&d.ra();for(const e of b.fa.values())for(const f of e)f.j();b.fa.clear();b.dc=a.timeScale;b.Ic=a.gameTime;d=a.listenerPos;b.g.listener.setPosition(d[0],d[1],d[2]);b.ta=a.isSilent;b.v.Db(b.ta);b.Sb=a.masterVolume;b.La.gain.value=b.Sb;d=[];for(const e of Object.values(a.effects))d.push(Promise.all(e.map(f=>lb(b,f))));await Promise.all(d);await Promise.all(a.playing.map(e=>rb(b,e,c)));S(b)}
async function sb(b,a){try{const c=b.g.suspend(a.time);b.vd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.Bb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>tb(d)),b.vd=!0);await c}catch(c){tb(c)}}
function ab(b){b.Lb||(b.Kc=!1,window.addEventListener("pointerup",b.va,!0),window.addEventListener("touchend",b.va,!0),window.addEventListener("click",b.va,!0),window.addEventListener("keydown",b.va,!0),b.Lb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ea)if(g.$a()===c)return await ub(g),g;if(f)return null;if(e&&(b.Wb||b.ud)){f=0;for(let h=0,m=b.ea.length;h<m;++h)g=b.ea[h],b.ea[f]=g,g.xa()?g.j():++f;b.ea.length=f}f="audio/webm; codecs=opus"===d&&!b.Kd;e&&f&&(b.ud=!0);c=!e||b.Wb||f?new self.ae(b,a,c,d,e,f):new self.Zd(b,a,c,d,e);b.ea.push(c);await ub(c);b.Cd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ca()}),b.Cd.add(a));return c}
function vb(b,a){return(a=b.fa.get(a.toLowerCase()))?a[0].R():b.wa()}function mb(b,a){let c=b.wa();var d=b.fa.get(a);if(d&&d.length){c=d[0].R();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.wa()):e.U(d[f+1].R())}}for(const f of R(b,a))d=c,e=f.F||f.N,e.disconnect(),e.connect(d);b.Ca&&b.Pc===a&&(b.Ca.disconnect(),b.Ca.connect(c))}function*R(b,a){if(a)for(const c of b.L)b=c.ba,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.la&&!b.la.S()&&(yield b.la)}
function wb(b,a,c){return c?b.v.Fe(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function xb(b,a){let c=0;for(let d=0,e=b.L.length;d<e;++d){const f=b.L[d];b.L[c]=f;f.M===a?f.j():++c}b.L.length=c}async function db(b,a,c,d,e,f){for(const g of b.L)if(g.$a()===c&&(g.hc()||f))return g.ba=e,g;a=await P(b,a,c,d,f);e="html5"===a.Cc?new self.$d(a.s,a,e):new self.be(a.s,a,e);b.L.push(e);return e}
function cb(b,a){let c=b.tb.get(a);if(!c){let d=null;c={Vc:0,promise:new Promise(e=>d=e),resolve:d};b.tb.set(a,c)}c.Vc++}function gb(b,a){a||(a=b.zd);return(b=b.tb.get(a))?b.promise:Promise.resolve()}function S(b){if(0<b.Ka.size)u(b);else for(const a of b.L)if(!a.H&&!a.S()){u(b);break}}function yb(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function nb(b){b.Nc||(b.Nc=!0,Promise.resolve().then(()=>zb(b)))}
function zb(b){const a={};for(const [c,d]of b.fa)a[c]=d.map(e=>e.Za());k(b,"fxstate",{fxstate:a});b.Nc=!1}
async function rb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await db(b,d,e,f,h,g)}catch(t){console.error("[Construct] Audio: error loading audio state: ",t);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.oa[0]=f[0],b.oa[1]=f[1],b.oa[2]=f[2],f=d.orient,b.na[0]=f[0],b.na[1]=f[1],b.na[2]=f[2],e.setPosition(...b.oa),e.setOrientation(...b.na),e.coneInnerAngle=d.cia,e.coneOuterAngle=
d.coa,e.coneOuterGain=d.cog,b.ka=d.uid):Q(b,!1);c.Play(m,p,q,0);a.isPlaying||c.bb();c.vc(a)}}}function tb(b){console.error("[Audio] Offline rendering error: ",b)}
self.Ya=class extends self.Fa{constructor(b){super(b,"audio");this.La=this.g=null;this.Lb=this.Kc=!1;this.va=()=>{if(!this.Kc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Lb&&(this.Kc=!0,window.removeEventListener("pointerup",this.va,!0),window.removeEventListener("touchend",this.va,!0),window.removeEventListener("click",this.va,!0),window.removeEventListener("keydown",
this.va,!0),this.Lb=!1)}};this.ea=[];this.L=[];this.la=null;this.zd="";this.Cd=new Set;this.Ad=-1;this.tb=new Map;this.Sb=1;this.ta=!1;this.Tc=0;this.dc=1;this.Ic=0;this.Ed="HRTF";this.pd="inverse";this.Fd=600;this.Dd=1E4;this.Hd=1;this.ud=this.Wb=!1;this.Kd=this.v.fe();this.fa=new Map;this.Ka=new Set;this.vd=this.Nc=!1;this.Pc="";this.Ca=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ca&&this.Ca.disconnect();this.Pc=c.toLowerCase();this.Ca=this.g.createMediaStreamSource(a);this.Ca.connect(vb(this,
this.Pc))};this.Jb=null;self.C3Audio_GetOutputStream=()=>{this.Jb||(this.Jb=this.g.createMediaStreamDestination(),this.La.connect(this.Jb));return this.Jb.stream};self.C3Audio_DOMInterface=this;r(this,[["create-audio-context",a=>$a(this,a)],["play",a=>bb(this,a)],["stop",a=>{a=a.tag;for(const c of R(this,a))c.ra()}],["stop-all",()=>{for(const a of this.L)a.ra()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of R(this,c))a?d.bb():d.Cb();S(this)}],["set-volume",a=>{const c=a.tag;a=a.vol;for(const d of R(this,
c))T(d,a)}],["fade-volume",a=>fb(this,a)],["set-master-volume",a=>{this.Sb=a.vol;this.La.gain.value=this.Sb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of R(this,c))Ab(d,a)}],["set-silent",a=>{this.ta=a.isSilent;this.v.Db(this.ta);for(const c of this.L)c.Hb()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of R(this,c))d.pc(a)}],["set-playback-rate",a=>hb(this,a)],["seek",a=>ib(this,a)],["preload",a=>jb(this,a)],["unload",a=>kb(this,a)],["unload-all",()=>{for(const a of this.ea)a.j();
this.ea.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.L)c.qc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>lb(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.fa.get(a.tag);!a||0>c||c>=a.length||(a[c].$(d,e,f,g),nb(this))}],["remove-effects",a=>{a=a.tag.toLowerCase();const c=this.fa.get(a);if(c&&c.length){for(const d of c)d.j();this.fa.delete(a);mb(this,a)}}],["tick",a=>{this.dc=a.timeScale;
this.Ic=a.gameTime;this.Ad=a.tickCount;if(0!==this.Tc)for(var c of this.L)c.za();(c=a.listenerPos)&&this.g.listener.setPosition(c[0],c[1],c[2]);for(const d of a.instPans){a=d.uid;for(const e of this.L)e.ka===a&&eb(e,d.x,d.y,d.angle)}}],["load-state",a=>ob(this,a)],["offline-render-audio",a=>sb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}X(){return this.g}wa(){return this.La}Ab(){return this.ta}ya(b){this.v.ya(b)}Ha(b){this.v.Ha(b)}Ia(){for(var b of this.Ka)b.Ia();b=this.g.currentTime;
for(var a of this.L)a.Ia(b);a=this.L.filter(c=>!c.H&&!c.S()).map(c=>c.Za());k(this,"state",{tickCount:this.Ad,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ka].map(c=>({tag:c.ba,index:c.wd,peak:c.Qa,rms:c.Gd,binCount:c.m.frequencyBinCount,freqBins:c.td}))});0===a.length&&0===this.Ka.size&&this.Mb&&(this.v.Ee(this.Ld),this.Mb=!1)}static le(b){return b*Za}static ad(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static ie(b){return Math.log(Math.max(Math.min(b,1),0))/
Math.log(10)*20}};self.qa.Xa(self.Ya);"use strict";function ub(b){b.Qb||(b.Qb=b.uc());return b.Qb}self.Yc=class{constructor(b,a,c,d,e){this.s=b;this.Le=a;this.Da=c;this.T=d;this.Ie=e;this.Cc="";this.Qb=null}j(){this.Qb=this.s=null}uc(){}X(){return this.s.X()}kc(){return this.Le}$a(){return this.Da}jc(){return this.T}xa(){return this.Ie}ca(){}};"use strict";
self.Zd=class extends self.Yc{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Cc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.nb=this.ob=null;this.K.addEventListener("canplaythrough",()=>!0);this.sb=this.X().createGain();this.qb=null;this.K.addEventListener("canplay",()=>{this.ob&&(this.ob(),this.nb=this.ob=null);!this.qb&&this.K&&(this.qb=this.X().createMediaElementSource(this.K),this.qb.connect(this.sb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Da}' error: `,f);this.nb&&(this.nb(f),this.nb=this.ob=null)})}j(){xb(this.s,this);this.sb.disconnect();this.sb=null;this.qb.disconnect();this.qb=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.j()}uc(){return new Promise((b,a)=>{this.ob=b;this.nb=a;this.K.src=this.Da})}P(){return this.K}ca(){return this.K.duration}};"use strict";
async function Bb(b){if(b.Aa)return b.Aa;var a=b.s.v;if("cordova"===a.A&&a.cd(b.Da)&&a.Nb)b.Aa=await a.zb(b.Da);else{a=await fetch(b.Da);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Aa=await a.arrayBuffer()}}async function Cb(b){if(b.da)return b.da;b.da=await wb(b.s,b.Aa,b.Ke);b.Aa=null}
self.ae=class extends self.Yc{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Cc="webaudio";this.da=this.Aa=null;this.Ke=!!f}j(){xb(this.s,this);this.da=this.Aa=null;super.j()}async uc(){try{await Bb(this),await Cb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Da}': `,b)}}ca(){return this.da?this.da.duration:0}};"use strict";let Db=0;
function Q(b,a){a=!!a;b.lb!==a&&(b.lb=a,b.lb?(b.F||(b.F=b.X().createPanner(),b.F.panningModel=b.s.Ed,b.F.distanceModel=b.s.pd,b.F.refDistance=b.s.Fd,b.F.maxDistance=b.s.Dd,b.F.rolloffFactor=b.s.Hd),b.N.disconnect(),b.N.connect(b.F),b.F.connect(b.wa())):(b.F.disconnect(),b.N.disconnect(),b.N.connect(b.wa())))}function T(b,a){b.Ea=a;b.N.gain.cancelScheduledValues(0);b.ib=-1;b.N.gain.value=b.lc()}function Ab(b,a){a=!!a;b.Ma!==a&&(b.Ma=a,b.Hb())}
function eb(b,a,c,d){b.lb&&(b.oa[0]=a,b.oa[1]=c,b.oa[2]=0,b.na[0]=Math.cos(d),b.na[1]=Math.sin(d),b.na[2]=0,b.F.setPosition(...b.oa),b.F.setOrientation(...b.na))}function U(b){return b.Oc?b.s.Ic:performance.now()/1E3}
self.Zc=class{constructor(b,a,c){this.s=b;this.M=a;this.ba=c;this.Ib=Db++;this.N=this.X().createGain();this.N.connect(this.wa());this.F=null;this.lb=!1;this.oa=[0,0,0];this.na=[0,0,0];this.H=!0;this.W=this.pa=this.I=!1;this.Ea=1;this.Ma=!1;this.ha=1;b=this.s.Tc;this.Oc=1===b&&!this.xa()||2===b;this.ib=this.ka=-1;this.Jd=!1}j(){this.M=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.N.disconnect();this.N=null}X(){return this.s.X()}wa(){return vb(this.s,this.ba)}kc(){return this.M.kc()}$a(){return this.M.$a()}jc(){return this.M.jc()}xa(){return this.M.xa()}S(){}hc(){}IsPlaying(){return!this.H&&
!this.I&&!this.S()}Ga(){}ca(){return this.M.ca()}Play(){}ra(){}bb(){}Cb(){}Ia(b){-1!==this.ib&&b>=this.ib&&(this.ib=-1,this.Jd&&this.ra(),yb(this.s,"fade-ended",this.ba,this.Ib))}lc(){const b=this.Ea;return isFinite(b)?b:0}Ab(){return this.s.Ab()}Hb(){}pc(){}za(){}oc(){}qc(){}mc(){}Za(){var b=this.Ib,a=this.ba,c=this.ca(),d=this.Ea,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.oa,orient:this.na,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ka}}else f=null;return{aiid:b,
tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ga(),playbackRate:this.ha,uid:this.ka,bufferOriginalUrl:this.kc(),bufferUrl:"",bufferType:this.jc(),isMusic:this.xa(),isLooping:this.W,isMuted:this.Ma,resumePosition:this.mc(),pan:f}}vc(b){var a=b.playbackRate;this.ha!==a&&(this.ha=a,this.za());Ab(this,b.isMuted)}};"use strict";
self.$d=class extends self.Zc{constructor(b,a,c){super(b,a,c);this.M.sb.connect(this.N);this.M.onended=()=>this.xc()}j(){this.ra();this.M.sb.disconnect();super.j()}P(){return this.M.P()}xc(){this.H=!0;this.ka=-1;yb(this.s,"ended",this.ba,this.Ib)}S(){return this.P().ended}hc(){return this.H?!0:this.S()}Ga(){let b=this.P().currentTime;this.W||(b=Math.min(b,this.ca()));return b}Play(b,a,c){const d=this.P();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.M.$a()}' to position '${c}': `,e)}this.s.ya(d);this.I=this.H=!1;this.W=b;this.ha=1}ra(){const b=this.P();b.paused||b.pause();this.s.Ha(b);this.H=!0;this.I=!1;this.ka=-1}bb(){if(!(this.I||this.H||this.S())){var b=this.P();b.paused||b.pause();this.s.Ha(b);this.I=!0}}Cb(){!this.I||this.H||this.S()||(this.s.ya(this.P()),this.I=!1)}Hb(){this.P().muted=this.Ma||this.Ab()}pc(b){b=!!b;this.W!==b&&(this.W=
b,this.P().loop=b)}za(){let b=this.ha;this.Oc&&(b*=this.s.dc);try{this.P().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}oc(b){if(!this.H&&!this.S())try{this.P().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}mc(){return this.Ga()}qc(b){b?this.IsPlaying()?(this.P().pause(),this.pa=!0):this.pa=!1:this.pa&&(this.s.ya(this.P()),this.pa=!1)}};"use strict";function V(b){b.o&&b.o.disconnect();b.o=null;b.cb=null}
self.be=class extends self.Zc{constructor(b,a,c){super(b,a,c);this.o=null;this.Ub=d=>this.xc(d);this.Jc=!0;this.cb=null;this.O=this.Vb=this.Xb=0;this.Qc=1}j(){this.ra();V(this);this.Ub=null;super.j()}xc(b){this.I||this.pa||b.target!==this.cb||(this.H=this.Jc=!0,this.ka=-1,V(this),yb(this.s,"ended",this.ba,this.Ib))}S(){return!this.H&&this.o&&this.o.loop||this.I?!1:this.Jc}hc(){return!this.o||this.H?!0:this.S()}Ga(){let b;b=this.I?this.O:this.Vb+(U(this)-this.Xb)*this.ha;this.W||(b=Math.min(b,this.ca()));
return b}Play(b,a,c,d){this.Qc=1;T(this,a);V(this);this.o=this.X().createBufferSource();this.o.buffer=this.M.da;this.o.connect(this.N);this.cb=this.o;this.o.onended=this.Ub;this.o.loop=b;this.o.start(d,c);this.I=this.H=this.Jc=!1;this.W=b;this.ha=1;this.Xb=U(this);this.Vb=c}ra(){if(this.o)try{this.o.stop(0)}catch(b){}this.H=!0;this.I=!1;this.ka=-1}bb(){this.I||this.H||this.S()||(this.O=this.Ga(),this.W&&(this.O%=this.ca()),this.I=!0,this.o.stop(0))}Cb(){!this.I||this.H||this.S()||(V(this),this.o=
this.X().createBufferSource(),this.o.buffer=this.M.da,this.o.connect(this.N),this.cb=this.o,this.o.onended=this.Ub,this.o.loop=this.W,T(this,this.Ea),this.za(),this.o.start(0,this.O),this.Xb=U(this),this.Vb=this.O,this.I=!1)}lc(){return super.lc()*this.Qc}Hb(){this.Qc=this.Ma||this.Ab()?0:1;T(this,this.Ea)}pc(b){b=!!b;this.W!==b&&(this.W=b,this.o&&(this.o.loop=b))}za(){let b=this.ha;this.Oc&&(b*=this.s.dc);this.o&&(this.o.playbackRate.value=b)}oc(b){this.H||this.S()||(this.I?this.O=b:(this.bb(),this.O=
b,this.Cb()))}mc(){return this.O}qc(b){b?this.IsPlaying()?(this.pa=!0,this.O=this.Ga(),this.W&&(this.O%=this.ca()),this.o.stop(0)):this.pa=!1:this.pa&&(V(this),this.o=this.X().createBufferSource(),this.o.buffer=this.M.da,this.o.connect(this.N),this.cb=this.o,this.o.onended=this.Ub,this.o.loop=this.W,T(this,this.Ea),this.za(),this.o.start(0,this.O),this.Xb=U(this),this.Vb=this.O,this.pa=!1)}vc(b){super.vc(b);this.O=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.X();this.wd=-1;this.T=this.ba="";this.l=null}j(){this.g=null}R(){}U(){}Za(){return{type:this.T,tag:this.ba,params:this.l}}}
self.Td=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.l=[a,c,d,e,f,g];this.u=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.C=this.g.createBiquadFilter();this.C.type=a;this.C.frequency.value=c;this.C.detune.value=d;this.C.Q.value=e;this.C.gain.vlaue=f;this.u.connect(this.C);this.u.connect(this.h);this.C.connect(this.i)}j(){this.u.disconnect();this.C.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.l[1]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.l[2]=a;Y(this,this.C.detune,a,c,d);break;case 3:this.l[3]=a;Y(this,this.C.Q,a,c,d);break;case 4:this.l[4]=a,Y(this,this.C.gain,a,c,d)}}};
self.Rd=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.l=[a,c,d];this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.pb=X(this);this.V=this.g.createDelay(a);this.V.delayTime.value=a;this.hb=X(this);this.hb.gain.value=c;this.u.connect(this.pb);this.u.connect(this.h);this.pb.connect(this.i);this.pb.connect(this.V);this.V.connect(this.hb);this.hb.connect(this.pb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.pb.disconnect();
this.V.disconnect();this.hb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){const e=self.Ya.ad;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.l[1]=e(a);Y(this,this.hb.gain,e(a),c,d);break;case 5:this.l[0]=a,Y(this,this.V.delayTime,a,c,d)}}};
self.Qd=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.l=[c,d];this.nd=this.md="";this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.gb=this.g.createConvolver();this.gb.normalize=c;this.gb.buffer=a;this.u.connect(this.gb);this.u.connect(this.h);this.gb.connect(this.i)}j(){this.u.disconnect();this.gb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}Za(){const b=super.Za();b.bufferOriginalUrl=this.md;b.bufferUrl="";b.bufferType=this.nd;return b}};
self.Ud=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.l=[a,c,d,e,f];this.u=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.jb=X(this);this.jb.gain.value=e;this.V=this.g.createDelay(a+c);this.V.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.J=X(this);this.J.gain.value=c;this.u.connect(this.V);this.u.connect(this.h);this.V.connect(this.i);this.V.connect(this.jb);this.jb.connect(this.V);this.B.connect(this.J);
this.J.connect(this.V.delayTime);this.B.start(0)}j(){this.B.stop(0);this.u.disconnect();this.V.disconnect();this.B.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();this.jb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.l[1]=a/1E3;Y(this,this.J.gain,a/1E3,
c,d);break;case 7:this.l[2]=a;Y(this,this.B.frequency,a,c,d);break;case 8:this.l[3]=a/100,Y(this,this.jb.gain,a/100,c,d)}}};
self.Wd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.l=[a,c,d,e,f,g];this.u=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.C=this.g.createBiquadFilter();this.C.type="allpass";this.C.frequency.value=a;this.C.detune.value=c;this.C.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.J=X(this);this.J.gain.value=e;this.u.connect(this.C);this.u.connect(this.h);this.C.connect(this.i);this.B.connect(this.J);this.J.connect(this.C.frequency);
this.B.start(0)}j(){this.B.stop(0);this.u.disconnect();this.C.disconnect();this.B.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.l[0]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.l[1]=a;Y(this,this.C.detune,a,c,d);
break;case 3:this.l[2]=a;Y(this,this.C.Q,a,c,d);break;case 6:this.l[3]=a;Y(this,this.J.gain,a,c,d);break;case 7:this.l[4]=a,Y(this,this.B.frequency,a,c,d)}}};self.Vd=class extends Z{constructor(b,a){super(b);this.T="gain";this.l=[a];this.m=X(this);this.m.gain.value=a}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}$(b,a,c,d){const e=self.Ya.ad;switch(b){case 4:this.l[0]=e(a),Y(this,this.m.gain,e(a),c,d)}}};
self.Yd=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.l=[a,c];this.m=X(this);this.m.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.J=X(this);this.J.gain.value=c/2;this.B.connect(this.J);this.J.connect(this.m.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.J.disconnect();this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=
a;Y(this,this.m.gain,1-a/2,c,d);Y(this,this.J.gain,a/2,c,d);break;case 7:this.l[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.Xd=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.l=[a,c];this.u=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.vb=X(this);this.vb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.vb.gain);this.B.start(0);this.u.connect(this.vb);this.u.connect(this.h);this.vb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.vb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.l[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.Sd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.l=[a,c,d,e,f];this.u=X(this);this.ac=X(this);this.$b=X(this);b=d;.01>b&&(b=.01);this.ac.gain.value=b;this.$b.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.ec=this.g.createWaveShaper();this.Fc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Fc[32768+e]=f,this.Fc[32768-
e-1]=-f;this.ec.curve=this.Fc;this.u.connect(this.ac);this.u.connect(this.h);this.ac.connect(this.ec);this.ec.connect(this.$b);this.$b.connect(this.i)}j(){this.u.disconnect();this.ac.disconnect();this.ec.disconnect();this.$b.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Pd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.l=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}$(){}};
self.Od=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.l=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.td=new Float32Array(this.m.frequencyBinCount);this.Id=new Uint8Array(a);this.Gd=this.Qa=0;b=this.s;b.Ka.add(this);S(b)}j(){this.s.Ka.delete(this);this.m.disconnect();super.j()}Ia(){this.m.getFloatFrequencyData(this.td);this.m.getByteTimeDomainData(this.Id);const b=this.m.fftSize;let a=this.Qa=0;for(var c=0;c<b;++c){let d=(this.Id[c]-
128)/128;0>d&&(d=-d);this.Qa<d&&(this.Qa=d);a+=d*d}c=self.Ya.ie;this.Qa=c(this.Qa);this.Gd=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}$(){}};"use strict";function Eb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Fb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.qa.Xa(class extends self.Fa{constructor(b){super(b,"browser");this.A="";r(this,[["get-initial-state",a=>{this.A=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Eb(this)],["alert",a=>this.wc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.yc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Fb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.cf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.A||"macos-wkwebview"===this.A)self.qa.Gb(!0),this.v.Bc({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===
a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(c):a.mozRequestFullScreen?a.mozRequestFullScreen(c):a.msRequestFullscreen?a.msRequestFullscreen(c):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.A||"macos-wkwebview"===this.A?(self.qa.Gb(!1),this.v.Bc({type:"set-fullscreen",
fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",
{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}wc(b){alert(b.message)}yc(b){b=b.isFocus;if("nwjs"===this.A){const a="nwjs"===this.A?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";
self.qa.Xa(class extends self.Fa{constructor(b){super(b,"mouse");r(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.v.G.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{k(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{k(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function Gb(b,a){a=a.type;let c=!0;0===a?c=await Hb():1===a&&(c=await Ib());k(b,"permission-result",{type:a,result:c})}async function Hb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Ib(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.qa.Xa(class extends self.Fa{constructor(b){super(b,"touch");n(this,"request-permission",a=>Gb(this,a))}});
